apply plugin: 'com.android.application'

boolean signConfigExists = project.hasProperty("SIGN_PROPS") && !project.property("SIGN_PROPS").toString().isEmpty() && new File(project.property("SIGN_PROPS")).exists()
if (signConfigExists) {
    Properties props = new Properties()
    props.load(new FileInputStream(file(project.property("SIGN_PROPS"))))

    android {
        signingConfigs {
            release {
                storeFile file(props['keystore'])
                storePassword props['keystore.password']
                keyAlias props['keystore.alias']
                keyPassword props['keystore.alias.password']
            }
        }
    }
}

android
{
    compileSdk = Integer.parseInt(project.COMPILE_SDK)

    defaultConfig
    {
        applicationId = project.PACKAGE
        minSdkVersion = project.MIN_SDK
        targetSdkVersion = project.TARGET_SDK
        versionCode = Integer.parseInt(project.VERSION_CODE)
        versionName = project.VERSION_NAME
    }

    buildFeatures
    {
        viewBinding = true
        buildConfig = true
    }

    buildTypes
    {
        release
        {
            minifyEnabled = true
            shrinkResources = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.txt'
            if (signConfigExists)
            {
                signingConfig = signingConfigs.release
            }
        }
        debug
        {
            applicationIdSuffix ".debug"
        }
    }

    compileOptions
    {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint
    {
        abortOnError = false
    }

    namespace = 'net.kzxiv.notify.client'
}

androidComponents {
    onVariants(selector().withBuildType("release")) { variant ->
        variant.outputs.forEach { output ->
            output.outputFileName.set("Notifikator-${variant.name}-${variant.buildType}.apk")
        }
    }
}
